import { integer, text } from "drizzle-orm/sqlite-core";

// =============================================================================
// Common Column Helpers for all tables
// =============================================================================

/** UUIDv4 primary key, generated by application code */
export const id = () =>
	text("id")
		.primaryKey()
		.$defaultFn(() => crypto.randomUUID());

/** ISO 8601 timestamp columns */
export const timestamps = {
	createdAt: text("created_at")
		.notNull()
		.$defaultFn(() => new Date().toISOString()),
	updatedAt: text("updated_at")
		.notNull()
		.$defaultFn(() => new Date().toISOString()),
};

/** Soft delete column (null = not deleted) */
export const softDelete = {
	deletedAt: text("deleted_at"),
};

/** Audit trail columns */
export const audit = {
	createdBy: text("created_by"),
	updatedBy: text("updated_by"),
};

/** Boolean column helper (SQLite INTEGER 0/1 -> TS boolean) */
export const boolean = (name: string) => integer(name, { mode: "boolean" });

/** JSON text column with default */
export const jsonText = (name: string, defaultValue = "{}") => text(name).notNull().default(defaultValue);
