import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { boolean, id, jsonText, timestamps } from "./_common.js";

export const users = sqliteTable(
	"users",
	{
		id: id(),
		email: text("email"),
		phone: text("phone"),
		externalId: text("external_id"),
		displayName: text("display_name"),
		...timestamps,
	},
	(table) => [
		index("idx_users_email").on(table.email),
		index("idx_users_phone").on(table.phone),
		index("idx_users_external_id").on(table.externalId),
	],
);

export const lineAccounts = sqliteTable("line_accounts", {
	id: id(),
	channelId: text("channel_id").unique().notNull(),
	name: text("name").notNull(),
	channelAccessToken: text("channel_access_token").notNull(),
	channelSecret: text("channel_secret").notNull(),
	isActive: boolean("is_active").notNull().default(true),
	...timestamps,
});

export const adminUsers = sqliteTable("admin_users", {
	id: id(),
	email: text("email").unique().notNull(),
	passwordHash: text("password_hash").notNull(),
	createdAt: text("created_at")
		.notNull()
		.$defaultFn(() => new Date().toISOString()),
});

export const staffMembers = sqliteTable(
	"staff_members",
	{
		id: id(),
		name: text("name").notNull(),
		email: text("email"),
		role: text("role").notNull(), // owner | admin | staff
		apiKey: text("api_key").unique().notNull(),
		isActive: boolean("is_active").notNull().default(true),
		...timestamps,
	},
	(table) => [index("idx_staff_members_api_key").on(table.apiKey), index("idx_staff_members_role").on(table.role)],
);

// ---------------------------------------------------------------------------
// MCP OAuth 2.1 — Dynamic Client Registration (RFC 7591)
// ---------------------------------------------------------------------------

export const mcpOauthClients = sqliteTable(
	"mcp_oauth_clients",
	{
		/** Client ID — generated by the server during dynamic registration */
		clientId: text("client_id").primaryKey(),
		/** Hashed client secret (null for public clients using PKCE only) */
		clientSecret: text("client_secret"),
		/** Human-readable client name for admin UI display */
		clientName: text("client_name").notNull(),
		/** JSON array of allowed redirect URIs per RFC 7591 */
		redirectUris: jsonText("redirect_uris", "[]"),
		/** JSON array of allowed grant types (default: authorization_code) */
		grantTypes: jsonText("grant_types", '["authorization_code"]'),
		/** Space-delimited scope string the client is registered for */
		scopes: text("scopes"),
		/** Epoch seconds when the client secret expires (0 = never, not recommended) */
		clientSecretExpiresAt: integer("client_secret_expires_at"),
		/** Epoch seconds when the client ID was issued */
		clientIdIssuedAt: integer("client_id_issued_at"),
		/** token_endpoint_auth_method — "none" for public clients */
		tokenEndpointAuthMethod: text("token_endpoint_auth_method"),
		...timestamps,
	},
	(table) => [index("idx_mcp_oauth_clients_name").on(table.clientName)],
);

// ---------------------------------------------------------------------------
// MCP OAuth 2.1 — Authorization Codes (PKCE flow)
// ---------------------------------------------------------------------------

export const mcpOauthCodes = sqliteTable(
	"mcp_oauth_codes",
	{
		/** The authorization code value */
		code: text("code").primaryKey(),
		/** FK to mcp_oauth_clients.client_id */
		clientId: text("client_id").notNull(),
		/** The PKCE code_challenge stored during /authorize */
		codeChallenge: text("code_challenge").notNull(),
		/** Space-delimited scopes granted */
		scopes: text("scopes").notNull(),
		/** Redirect URI used in the authorization request */
		redirectUri: text("redirect_uri").notNull(),
		/** Epoch seconds when this code expires */
		expiresAt: integer("expires_at").notNull(),
		/** Staff member ID who authorized (null for env API_KEY) */
		staffId: text("staff_id"),
		...timestamps,
	},
	(table) => [
		index("idx_mcp_oauth_codes_client").on(table.clientId),
		index("idx_mcp_oauth_codes_expires").on(table.expiresAt),
	],
);

// ---------------------------------------------------------------------------
// MCP OAuth 2.1 — Tokens (access + refresh)
// ---------------------------------------------------------------------------

export const mcpOauthTokens = sqliteTable(
	"mcp_oauth_tokens",
	{
		/** The token value (hashed for storage security) */
		tokenHash: text("token_hash").primaryKey(),
		/** Token type: "access" or "refresh" */
		tokenType: text("token_type").notNull(), // "access" | "refresh"
		/** FK to mcp_oauth_clients.client_id */
		clientId: text("client_id").notNull(),
		/** Space-delimited scopes for this token */
		scopes: text("scopes").notNull(),
		/** Epoch seconds when this token expires */
		expiresAt: integer("expires_at").notNull(),
		/** Staff member ID who authorized (null for env API_KEY) */
		staffId: text("staff_id"),
		/** Whether this token has been revoked */
		isRevoked: boolean("is_revoked").notNull().default(false),
		...timestamps,
	},
	(table) => [
		index("idx_mcp_oauth_tokens_client").on(table.clientId),
		index("idx_mcp_oauth_tokens_expires").on(table.expiresAt),
		index("idx_mcp_oauth_tokens_type").on(table.tokenType),
	],
);
